repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/python/black
    rev: '22.6.0'
    hooks:
      - id: black
        language_version: python3.8
        args: [
            --skip-string-normalization,
            -l 120,
        ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-docstring-first
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: check-symlinks
      - id: flake8
